receivers:
  # collect aws ecs metrics
  awsecscontainermetrics:
    collection_interval: 30s

  # listen for signals on otlp endpoint
  otlp:
    protocols:
      grpc:
      http:
  
  # statsd metric listener
  statsd:
    endpoint: 0.0.0.0:8125
    aggregation_interval: 60s

  # prometheus self-monitoring
  prometheus/selfmon:
    config:
      scrape_configs:
      - job_name: opentelemetry-collector
        scrape_interval: 30s
        static_configs:
        - targets:
          - localhost:8888

processors:
  # batch processor
  batch:
    send_batch_max_size: 1000
    timeout: 30s
    send_batch_size: 800
  # memory limiter
  memory_limiter:
    check_interval: 1s
    limit_percentage: 70
    spike_limit_percentage: 30
  # cumulative sum to delta metrics
  cumulativetodelta: {}
  # dynatrace relevant attributes
  resource/dt:
    attributes:
    - key: telemetry.sdk.name
      value: opentelemetry
      action: insert
    - key: dynatrace.otel.collector
      value: aws-ecs-fargate
      action: insert
    - key: aws.ecs.service.name
      value: unknown
      action: insert

  # ecs relevant attributes
  attributes/ecs:
    actions:
    - key: service.name
      from_attribute: aws.ecs.task.family 
      action: insert
    - key: service.namespace
      from_attribute: aws.ecs.cluster.name
      action: insert

exporters:
  # otlphttp to dynatrace using environment variable
  otlphttp/dynatrace:
    endpoint: "${env:DT_ENDPOINT}"
    headers:
      Authorization: "Api-Token ${env:DT_API_TOKEN}"
  
  # debug
  debug:
    verbosity: basic
    sampling_initial: 5
    sampling_thereafter: 20

service:
  telemetry:
    logs:
      level: "info"
      encoding: "json"
    metrics:
      level: "normal"
      address: localhost:8888
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource/dt, attributes/ecs, batch]
      exporters: [debug, otlphttp/dynatrace]
    metrics:
      receivers: [otlp, awsecscontainermetrics, statsd, prometheus/selfmon]
      processors: [memory_limiter, resource/dt, attributes/ecs, cumulativetodelta, batch]
      exporters: [debug, otlphttp/dynatrace]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource/dt, attributes/ecs, batch]
      exporters: [debug, otlphttp/dynatrace]
